### ISSUE TITLE
Crashing when launching with "-s session-file.json" (master)

### ISSUE THREAD

**Issue by dsboger** [gnunn1/terminix#550]
When I try to launch terminix with the command `terminix -s session-file.json` it segfaults. The output/backtrace taken with gdb is below. As usual, I'm running terminix-git from AUR, i.e. compiled from master with LDC. Let me know if I can provide more info. Thanks!

```
(gdb) run -s .terminix-layout.json 
Starting program: /usr/bin/terminix -s .terminix-layout.json
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffe7c1b700 (LWP 4049)]
[New Thread 0x7fffe741a700 (LWP 4050)]
[New Thread 0x7fffe658a700 (LWP 4051)]

Thread 1 "terminix" received signal SIGSEGV, Segmentation fault.
0x000000000051e5f9 in ?? ()
(gdb) bt
#0  0x000000000051e5f9 in  ()
#1  0x000000000052383b in  ()
#2  0x0000000000528721 in  ()
#3  0x00000000005288f1 in  ()
#4  0x0000000000528c92 in  ()
#5  0x000000000050fc9e in  ()
#6  0x000000000050aa5d in  ()
#7  0x00000000004ed0ff in  ()
#8  0x00000000004eeb3c in  ()
#9  0x00007ffff74510b9 in gio.Application.Application.callBackActivate(gtkc.giotypes.GApplication*, gio.Application.Application) () at /usr/lib/libgtkd-3.so.0
#10 0x00007ffff3e32f75 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#11 0x00007ffff3e44f82 in  () at /usr/lib/libgobject-2.0.so.0
#12 0x00007ffff3e4dbcc in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#13 0x00007ffff3e4dfaf in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#14 0x00000000004eddf6 in  ()
#15 0x00007ffff3c201c8 in ffi_call_unix64 () at /usr/lib/libffi.so.6
#16 0x00007ffff3c1fc2a in ffi_call () at /usr/lib/libffi.so.6
#17 0x00007ffff3e337ae in g_cclosure_marshal_generic () at /usr/lib/libgobject-2.0.so.0
#18 0x00007ffff3e32f75 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#19 0x00007ffff3e44f82 in  () at /usr/lib/libgobject-2.0.so.0
#20 0x00007ffff3e4d66f in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#21 0x00007ffff3e4dfaf in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#22 0x00007fffee82c293 in  () at /usr/lib/libgio-2.0.so.0
#23 0x00007fffee82e2e4 in  () at /usr/lib/libgio-2.0.so.0
#24 0x00007fffee82e4b2 in g_application_run () at /usr/lib/libgio-2.0.so.0
#25 0x000000000053237d in  ()
#26 0x00007ffff5dde95f in rt.dmain2._d_run_main(int, char**, extern(C) int(char[][]) function).runAll().__lambda1() () at /usr/lib/libdruntime-ldc.so.70
#27 0x00007ffff5dde8a4 in rt.dmain2._d_run_main(int, char**, extern(C) int(char[][]) function).tryExec(scope void() delegate) () at /usr/lib/libdruntime-ldc.so.70
#28 0x00007ffff5dde7cd in _d_run_main () at /usr/lib/libdruntime-ldc.so.70
#29 0x00007ffff528f291 in __libc_start_main () at /usr/lib/libc.so.6
#30 0x000000000049f39a in  ()
```

**Comment by gnunn1** [comment]
Can you test if this commit corrects the issue please, thanks.

**Comment by dsboger** [comment]
Unfortunately nothing changed. Please, note that the file actually exists. I've tried with an absolute path also, same crash. Maybe it is something about the content of the file?

```
{
    "child": {
        "child1": {
            "directory": "\/home\/dsboger",
            "height": 830,
            "profile": "2b7c4080-0ddd-46c5-8f23-563fd3ba789d",
            "readOnly": false,
            "synchronizedInput": true,
            "type": "Terminal",
            "width": 769
        },
        "child2": {
            "directory": "\/home\/dsboger",
            "height": 830,
            "profile": "2b7c4080-0ddd-46c5-8f23-563fd3ba789d",
            "readOnly": false,
            "synchronizedInput": true,
            "type": "Terminal",
            "width": 763
        },
        "orientation": 0,
        "position": 50,
        "type": "Paned"
    },
    "height": 830,
    "name": "Default",
    "synchronizedInput": false,
    "type": "Session",
    "version": "1.0",
    "width": 1537
}
```

**Comment by gnunn1** [comment]
Reproduced it, I'm on Wayland and this only happens under X11.
