### ISSUE TITLE
Moving transparency widget back and forth eventually causes SEG Fault

### ISSUE THREAD

**Issue by gnunn1** [gnunn1/terminix#8]
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff1d758a7 in g_slice_alloc () from /usr/lib/libglib-2.0.so.0
(gdb) backtrace
#0  0x00007ffff1d758a7 in g_slice_alloc () from /usr/lib/libglib-2.0.so.0
#1  0x00007ffff1d75be1 in g_slice_copy () from /usr/lib/libglib-2.0.so.0
#2  0x000000000084a785 in gdk.RGBA.RGBA.this() (this=0x7ffff7f8ac00) at ../../../.dub/packages/gtk-d-3.2.1/src/gdk/RGBA.d:71
#3  0x0000000000831d67 in gx.terminix.terminal.terminal.Terminal.applyPreference(immutable(char)[]) (this=0x7ffff7f2f000, key=...) at source/gx/terminix/terminal/terminal.d:641
#4  0x0000000000833d8c in gx.terminix.terminal.terminal.Terminal.this(immutable(char)[]).__dgliteral2!(gio.Settings.Settings).__dgliteral2(immutable(char)[], gio.Settings.Settings) (this=0x7ffff7f23ac0, Settings=0x7ffff7eb2a00, key=...) at source/gx/terminix/terminal/terminal.d:1020
#5  0x0000000000877b73 in gio.Settings.Settings.callBackChanged(gtkc.giotypes.GSettings*, char*, gio.Settings.Settings) (settingsStruct=0x112e6b0, 
    key=0x11a30f7 "background-transparency-percent", _settings=0x7ffff7eb2a00) at ../../../.dub/packages/gtk-d-3.2.1/src/gio/Settings.d:1547
#6  0x00007ffff1227aca in g_cclosure_marshal_VOID__STRINGv () from /usr/lib/libgobject-2.0.so.0
#7  0x00007ffff1225244 in ?? () from /usr/lib/libgobject-2.0.so.0
#8  0x00007ffff123fa46 in g_signal_emit_valist () from /usr/lib/libgobject-2.0.so.0
#9  0x00007ffff124012f in g_signal_emit () from /usr/lib/libgobject-2.0.so.0
#10 0x00007ffff0d2ec2c in ?? () from /usr/lib/libgio-2.0.so.0
#11 0x00007ffff18e11f0 in ffi_call_unix64 () from /usr/lib/libffi.so.6
#12 0x00007ffff18e0c58 in ffi_call () from /usr/lib/libffi.so.6
#13 0x00007ffff1225d65 in g_cclosure_marshal_generic_va () from /usr/lib/libgobject-2.0.so.0
#14 0x00007ffff1225244 in ?? () from /usr/lib/libgobject-2.0.so.0
#15 0x00007ffff123f558 in g_signal_emit_valist () from /usr/lib/libgobject-2.0.so.0
#16 0x00007ffff124012f in g_signal_emit () from /usr/lib/libgobject-2.0.so.0
#17 0x00007ffff0d2e86c in ?? () from /usr/lib/libgio-2.0.so.0
#18 0x00007ffff0d29f9a in ?? () from /usr/lib/libgio-2.0.so.0
#19 0x00007ffff1d59cf5 in g_main_context_invoke_full () from /usr/lib/libglib-2.0.so.0
#20 0x00007ffff0d2a0a4 in ?? () from /usr/lib/libgio-2.0.so.0
#21 0x00007fffe8ac0414 in ?? () from /usr/lib/gio/modules/libdconfsettings.so
#22 0x00007fffe8ac1519 in ?? () from /usr/lib/gio/modules/libdconfsettings.so
#23 0x00007fffe8abfedc in ?? () from /usr/lib/gio/modules/libdconfsettings.so
#24 0x00007ffff0d2aad4 in ?? () from /usr/lib/libgio-2.0.so.0
#25 0x00007ffff0d2f503 in ?? () from /usr/lib/libgio-2.0.so.0
#26 0x00007ffff0d2f718 in ?? () from /usr/lib/libgio-2.0.so.0
#27 0x00007ffff1225015 in g_closure_invoke () from /usr/lib/libgobject-2.0.so.0
#28 0x00007ffff1237061 in ?? () from /usr/lib/libgobject-2.0.so.0
#29 0x00007ffff123fdfc in g_signal_emit_valist () from /usr/lib/libgobject-2.0.so.0
#30 0x00007ffff124012f in g_signal_emit () from /usr/lib/libgobject-2.0.so.0
#31 0x00007ffff1229544 in ?? () from /usr/lib/libgobject-2.0.so.0
#32 0x00007fffedb4d596 in ?? () from /usr/lib/libgtk-3.so.0
#33 0x00007ffff122bae9 in g_object_notify_by_pspec () from /usr/lib/libgobject-2.0.so.0
#34 0x00007fffedcc26f3 in ?? () from /usr/lib/libgtk-3.so.0
#35 0x00007fffedc625b1 in ?? () from /usr/lib/libgtk-3.so.0
#36 0x00007ffff1225015 in g_closure_invoke () from /usr/lib/libgobject-2.0.so.0
```

**Comment by gnunn1** [comment]
```
(gdb) frame 3
#3  0x0000000000831d67 in gx.terminix.terminal.terminal.Terminal.applyPreference(immutable(char)[]) (this=0x7ffff7f2f000, key=...) at source/gx/terminix/terminal/terminal.d:641
641	                palette[i] = new RGBA();
(gdb) frame 2
#2  0x000000000084a785 in gdk.RGBA.RGBA.this() (this=0x7ffff7f8ac00) at ../../../.dub/packages/gtk-d-3.2.1/src/gdk/RGBA.d:71
71			this(gdk_rgba_copy(&rgba));
```

**Comment by gnunn1** [comment]
```
#2  0x000000000084a785 in gdk.RGBA.RGBA.this() (this=0x7ffff7f8ac00) at ../../../.dub/packages/gtk-d-3.2.1/src/gdk/RGBA.d:71
71			this(gdk_rgba_copy(&rgba));
(gdb) print rgba
$1 = {red = 0, green = 0, blue = 0, alpha = 0}
```
